
# This script takes the single-fault result file generated by ZOIX as input,
# then rule out the UB (Untested Blocked) and NO (Not Observed) faults,
# and generate the single-fault list in a read-friendly format for sff_gen_RTL.py script.

import io

##############################################

file_name = 'user_coverage.sff'     # the single-fault result file generated by ZOIX
output_file = 'fault_list_cells.txt'

##############################################

# Read .sff file
fault_list = list()
output_list = list()

fid = open(file_name,'r')
fault_list = fid.readlines()
# Rule out the UB and NO faults, keep DD and ND only
for line in fault_list:
    if line.find(' DD ~ ')>-1 or line.find(' ND ~ ')>-1:
        # Find cell names between certain texts
        cell = line[line.find(' {VARI "'):line.find('"}')]
        cell = cell.replace(' {VARI "','')
        output_list.append(cell)
# Delete the duplicated cells and report
print('Total cells: '+str(len(output_list)))
output_list = set(output_list)
print('Total cells after sorted: '+str(len(output_list)))
fid.close()

fid = open(output_file,'w')
for cell in output_list:
    fid.write(cell+' ')
fid.close()